const SEARCH_FRIENDS_START = 'SEARCH_FRIENDS_START';
const SEARCH_FRIENDS_SUCCESS = 'SEARCH_FRIENDS_SUCCESS';
const SEARCH_FRIENDS_FAILURE = 'SEARCH_FRIENDS_FAILURE';
const SEND_FRIEND_REQUEST_START = 'SEND_FRIEND_REQUEST_START';
const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS';
const SEND_FRIEND_REQUEST_FAILURE = 'SEND_FRIEND_REQUEST_FAILURE';
const GET_FRIENDS_REQUESTS_START = 'GET_FRIENDS_REQUESTS_START';
const GET_FRIENDS_REQUESTS_SUCCESS = 'GET_FRIENDS_REQUESTS_SUCCESS';
const GET_FRIENDS_REQUESTS_FAILURE = 'GET_FRIENDS_REQUESTS_FAILURE';
const ACCEPT_FRIEND_REQUEST_START = 'ACCEPT_FRIEND_REQUEST_START';
const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';
const ACCEPT_FRIEND_REQUEST_FAILURE = 'ACCEPT_FRIEND_REQUEST_FAILURE';

export {
    SEARCH_FRIENDS_START,
    SEARCH_FRIENDS_SUCCESS,
    SEARCH_FRIENDS_FAILURE,
    SEND_FRIEND_REQUEST_START,
    SEND_FRIEND_REQUEST_SUCCESS,
    SEND_FRIEND_REQUEST_FAILURE,
    GET_FRIENDS_REQUESTS_START,
    GET_FRIENDS_REQUESTS_SUCCESS,
    GET_FRIENDS_REQUESTS_FAILURE,
    ACCEPT_FRIEND_REQUEST_START,
    ACCEPT_FRIEND_REQUEST_SUCCESS,
    ACCEPT_FRIEND_REQUEST_FAILURE
}