const SEARCH_FRIENDS_START = 'SEARCH_FRIENDS_START';
const SEARCH_FRIENDS_SUCCESS = 'SEARCH_FRIENDS_SUCCESS';
const SEARCH_FRIENDS_FAILURE = 'SEARCH_FRIENDS_FAILURE';

export {
    SEARCH_FRIENDS_START,
    SEARCH_FRIENDS_SUCCESS,
    SEARCH_FRIENDS_FAILURE
}