const SEARCH_FRIENDS_START = 'SEARCH_FRIENDS_START';
const SEARCH_FRIENDS_SUCCESS = 'SEARCH_FRIENDS_SUCCESS';
const SEARCH_FRIENDS_FAILURE = 'SEARCH_FRIENDS_FAILURE';
const ADD_FRIEND_START = 'ADD_FRIEND_START';
const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';
const GET_FRIENDS_REQUESTS_START = 'GET_FRIENDS_REQUESTS_START';
const GET_FRIENDS_REQUESTS_SUCCESS = 'GET_FRIENDS_REQUESTS_SUCCESS';
const GET_FRIENDS_REQUESTS_FAILURE = 'GET_FRIENDS_REQUESTS_FAILURE';

export {
    SEARCH_FRIENDS_START,
    SEARCH_FRIENDS_SUCCESS,
    SEARCH_FRIENDS_FAILURE,
    ADD_FRIEND_START,
    ADD_FRIEND_SUCCESS,
    ADD_FRIEND_FAILURE,
    GET_FRIENDS_REQUESTS_START,
    GET_FRIENDS_REQUESTS_SUCCESS,
    GET_FRIENDS_REQUESTS_FAILURE
}