const REGISTER_START = 'REGISTER_START';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';
const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGOUT_START =  'LOGOUT_START';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
const GUEST_MODE_START = 'GUEST_MODE_START';
const GUEST_MODE_SUCCESS = 'GUEST_MODE_SUCCESS';
const GUEST_MODE_FAILURE = 'GUEST_MODE_FAILURE';
const UPDATE_START = 'UPDATE_START';
const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
const UPDATE_FAILURE = 'UPDATE_FAILURE';
const GETUSERINFO_START = 'GETUSERINFO_START';
const GETUSERINFO_SUCCESS = 'GETUSERINFO_SUCCESS';
const GETUSERINFO_FAILURE = 'GETUSERINFO_FAILURE';
const UPDATESETTINGSLIST_START = 'UPDATESETTINGSLIST_START';
const UPDATESETTINGSLIST_SUCCESS = 'UPDATESETTINGSLIST_SUCCESS';
const UPDATESETTINGSLIST_FAILURE = 'UPDATESETTINGSLIST_FAILURE';
const GETSETTINGSLIST_START = 'GETUSERSETTINGLIST_START';
const GETSETTINGSLIST_SUCCESS = 'GETSETTINGSLIST_SUCCESS';
const GETSETTINGSLIST_FAILURE = 'GETSETTINGSLIST_FAILURE';

export {
    REGISTER_START,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    LOGIN_START,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_START,
    LOGOUT_SUCCESS,
    LOGOUT_FAILURE,
    GUEST_MODE_START,
    GUEST_MODE_SUCCESS,
    GUEST_MODE_FAILURE,
    UPDATE_START,
    UPDATE_SUCCESS,
    UPDATE_FAILURE,
    GETUSERINFO_START,
    GETUSERINFO_SUCCESS,
    GETUSERINFO_FAILURE,
    UPDATESETTINGSLIST_START,
    UPDATESETTINGSLIST_SUCCESS,
    UPDATESETTINGSLIST_FAILURE,
    GETSETTINGSLIST_START,
    GETSETTINGSLIST_SUCCESS,
    GETSETTINGSLIST_FAILURE
}